<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>rkt</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\(</string>
	<key>foldingStopMarker</key>
	<string>\)</string>
	<key>name</key>
	<string>Racket (Custom)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>#\|</string>
			<key>end</key>
			<string>\|#</string>
			<key>name</key>
			<string>comment.block.source.racket</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.source.racket</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(;).*$\n?</string>
			<key>name</key>
			<string>comment.line.documentation.source.racket</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.source.racket</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(#!).*$\n?</string>
			<key>name</key>
			<string>comment.line.source.racket</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(#).*$\n?</string>
			<key>name</key>
			<string>constant.character.source.racket</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.function-type.source.racket</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.source.racket</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>meta.function.source.racket</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\b(?i:(defun|define|defmethod|defmacro))\b)(\s+)\((((\w|\-|\!|\?)*) ?((\w|\-|\!|\?) ?)*)</string>
			<key>name</key>
			<string>meta.function.source.racket</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.function-type.source.racket</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.source.racket</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\b(?i:(defun|define|defmethod|defmacro))\b)(\s+)((\w|\-|\!|\?)*)</string>
			<key>name</key>
			<string>meta.function.source.racket</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.source.racket</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(#)(\w|[\\+-=&lt;&gt;'"&amp;#])+</string>
			<key>name</key>
			<string>constant.character.source.racket</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.source.racket</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.source.racket</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\*)(\S*)(\*)</string>
			<key>name</key>
			<string>variable.other.global.source.racket</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:case|do|let|loop|if|else|when)\b</string>
			<key>name</key>
			<string>keyword.control.source.racket</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:eq|neq|and|or)\b</string>
			<key>name</key>
			<string>keyword.operator.source.racket</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\*|\/|\-|\+|=|&lt;|&gt;)</string>
			<key>name</key>
			<string>keyword.operator.source.racket</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:null|nil)\b</string>
			<key>name</key>
			<string>constant.language.source.racket</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:cons|car|cdr|cond|define|lambda|format|setq|setf|quote|eval|append|list|listp|memberp|t|load|progn)\b</string>
			<key>name</key>
			<string>support.function.source.racket</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(L|l|UL|ul|u|U|F|f|ll|LL|ull|ULL)?\b</string>
			<key>name</key>
			<string>constant.numeric.source.racket</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.source.racket</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.source.racket</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.source.racket</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.source.racket</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.racket</string>
	<key>uuid</key>
	<string>afda310a-1b2e-4b97-a0f7-13819a0ee21f</string>
</dict>
</plist>
